### ISSUE TITLE
optionally read input from /etc/ssh/ssh_config in addition to ~/.ssh/config

### ISSUE THREAD

**Issue by turbomettwurst** [ibrokemycomputer/gnome-shell-extension-ssh-quick-connect#1]
Title pretty much says everything.
I have all my Hosts configured globally in /etc/ssh/ssh_config. It would be great if those could be read in as well

**Comment by ibrokemycomputer** [comment]
@turbomettwurst I agree! It is on my uncommitted TODO list :smile: Hopefully I'll get to it this week, I have a quick optimization to do so I can publish it in the GNOME extension directory but I'll make this request priority #2!

**Comment by ibrokemycomputer** [comment]
Hi @turbomettwurst , I just added this to the plugin! 
Thank you for the suggestion. 

I want to make it more user-friendly by using a nicer list that is loaded based on the files provided, and has the options to sort/hide/etc the files AND the Hosts it finds in those files. "Baby steps" I suppose...

https://github.com/ibrokemycomputer/gnome-shell-extension-ssh-quick-connect/pull/5
