### ISSUE TITLE
Last update adapted to GNOME Shell 43 doesn't work on GNOME Shell 3.36.9

### ISSUE THREAD

**Issue by muchahagrande** [ibrokemycomputer/gnome-shell-extension-ssh-quick-connect#11]
Hi, as the title say, the last update stopped working on 3.36.9 on Ubuntu 20.04.
I reverted to the previous version for now.

**Comment by ibrokemycomputer** [comment]
@muchahagrande My apologies! I just pushed up a fix, waiting for review but the new version should be up on the GNOME Shell Extensions site soon!

**Comment by slawekmikula** [comment]
Thanks !

**Comment by muchahagrande** [comment]
Hi @ibrokemycomputer. No problem. I'll wait for the fix. Thank you for the work and for the response.

**Comment by ibrokemycomputer** [comment]
There was a click listener issue with thee build I pushed earlier -a "real" fix is pending approval! Sorry about the back and forth

**Comment by slawekmikula** [comment]
Updated and checked. Works OK! Thanks.

**Comment by ibrokemycomputer** [comment]
Awesome, glad to hear! I'll close thiis out.
