### ISSUE TITLE
Last update doesn't work on GNOME Shell 3.36.9

### ISSUE THREAD

**Issue by muchachagrande** [ibrokemycomputer/gnome-shell-extension-ssh-quick-connect#14]
Hi, I tested the last pushed version and it still not working on Ubuntu 20.04 gnome 3.36.9

This is the log shown when I press the config button on the extension manager:

```
Error: Requiring Adw, version none: Typelib file for namespace 'Adw' (any version) not found

Stack trace:
  @/home/fjm/.local/share/gnome-shell/extensions/ssh-quick-connect@ibrokemy.computer/prefs.js:1:27
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
```

This is the screenshot of the extension manager:

![imagen](https://user-images.githubusercontent.com/20299175/201715124-5ca93d1f-a2d3-4841-9d47-5f60cf809dbc.png)

Thank you in advance and cheers

**Comment by ibrokemycomputer** [comment]
@muchahagrande Please try to install `libadwaita-1-0`.

```bash
sudo apt install libadwaita-1-0
```

**Comment by muchahagrande** [comment]
Hi @ibrokemycomputer.
The package couldn't be located.

**Comment by ibrokemycomputer** [comment]
My mistake - that package is only available on higher versions of Ubuntu. 

I will do some more digging and try to find what is causing this error. 
I'll have to spin up a Ubuntu 20.04 VM. I'm in the US we have a holiday this week - but hopefully I can make time for it today! :)

**Comment by muchahagrande** [comment]
> I'll have to spin up a Ubuntu 20.04 VM. I'm in the US we have a holiday this week - but hopefully I can make time for it today! :)

Sure, have a happy holiday and thank you very much.

**Comment by ibrokemycomputer** [comment]
Sorry for the delayed response everyone. Work/the tech industry has been a bit chaotic these past few months. Seeing that there is now a new LTS version of Ubuntu I don't know that I am going to maintain pre-Gnome 40 support.

**Comment by ibrokemycomputer** [comment]
I am closing this and dropping support for pre-40. I recommend upgrading to the latest LTS!

There are still old versions/releases in this repo that you should be able to use. I have also left one version of the extension with < Gnome 40 support active on the extension page.

**Comment by muchachagrande** [comment]
Ok. thanks anyway
