### ISSUE TITLE
Support for Gnome 44

### ISSUE THREAD

**Issue by fabaff** [ibrokemycomputer/gnome-shell-extension-ssh-quick-connect#17]
It would be much appreciated if support for Gnome 44 is added.

Thanks

**Comment by ibrokemycomputer** [comment]
I just updated the repo and also submitted a new zip the Gnome Shell Extension Website (v10). 
Should be approved soon! For now you can manually install if needed.

**Comment by ibrokemycomputer** [comment]
@fabaff This is now available on the [extension page](https://extensions.gnome.org/extension/3237/ssh-quick-connect/) and has also been set as the [latest release](https://github.com/ibrokemycomputer/gnome-shell-extension-ssh-quick-connect/releases/tag/gnome-shell-44-update). Thank you for reminding me about the Gnome shell update!
