### ISSUE TITLE
Quick Connect stopped working

### ISSUE THREAD

**Issue by hi-flyer** [ibrokemycomputer/gnome-shell-extension-ssh-quick-connect#19]
ssh-quick-connect has been working great until recently. I am on ubuntu 22.04 and up to date on system.
this is the error I get in syslog when I attempt to start a session.

May  2 10:57:30 BEE-XPS15-9500 gnome-shell[3769]: JS ERROR: ReferenceError: isDebian is not defined#012getTerminalCommand@/home/beckstein/.local/share/gnome-shell/extensions/ssh-quick-connect@ibrokemy.computer/extension.js:184:9#012sshToItem@/home/beckstein/.local/share/gnome-shell/extensions/ssh-quick-connect@ibrokemy.computer/extension.js:121:32#012createMenu/</<@/home/beckstein/.local/share/gnome-shell/extensions/ssh-quick-connect@ibrokemy.computer/extension.js:85:43#012addAction/<@resource:///org/gnome/shell/ui/popupMenu.js:555:21#012activate@resource:///org/gnome/shell/ui/popupMenu.js:197:14#012vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:141:14

any idea how to fix the problem?

**Comment by ibrokemycomputer** [comment]
@hi-flyer Thanks for catching that! The master branch is now fixed.

I just uploaded a new version to the Gnome Shell [Extension Page](https://extensions.gnome.org/extension/3237/ssh-quick-connect/). 
Look for version 12 (pending approval)

I also created a new [release](https://github.com/ibrokemycomputer/gnome-shell-extension-ssh-quick-connect/releases/tag/44.1)
