### ISSUE TITLE
Broken on Gnome 45 (Ubuntu 23.10)

### ISSUE THREAD

**Issue by hcs-catchscan** [ibrokemycomputer/gnome-shell-extension-ssh-quick-connect#24]
The SSH Quick Connect extension is broken on a stock Ubuntu 23.10 install. The following error is emitted:

> The settings of extension ssh-quick-connect@ibrokemy.computer had an error:
> ```
> SyntaxError: import declarations may only appear at top level of a module
>```
>
> Stack trace:
> ```
>@file:///home/hcs/.local/share/gnome-shell/extensions/ssh-quick-connect@ibrokemy.computer/prefs.js:3:24
>_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
>```

**Comment by ibrokemycomputer** [comment]
@hcs-catchscan #23 (theoretically) just needed a `metadata.json` update. 

**However**, GNOME 45 _did_ introduce breaking changes with a switch to module imports (which I'm just now learning... sorry I've been behind!)

https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

I'll try to get this extension updated and packaged before next week but no promises :/

**Comment by laudecioliveira** [comment]
Hi, I have a forked your code and did some changes and get it working on  gnome 45. 
I will try to propose a merge so you be able to test the code..

**Comment by laudecioliveira** [comment]
Gnome 45 working version on https://github.com/laudecioliveira/gnome-shell-extension-ssh-quick-connect , how can I propose a merge?

**Comment by ibrokemycomputer** [comment]
Thank you! I started the conversion over the weekend but didn't get to finishing it. I'll happily take a look and merge it.

You'll need to create a [new pull request](https://github.com/ibrokemycomputer/gnome-shell-extension-ssh-quick-connect/compare). If you aren't sure how to I can do that for you. I haven't looked at your repo yet, but if you'd like me to submit the PR (merge) can you confirm which branch to use?

**Comment by ibrokemycomputer** [comment]
@laudecioliveira I merged this in :) Once I test it I'll package it up and upload it to the Gnome Extensions site. 


Thank you!

**Comment by ibrokemycomputer** [comment]
@laudecioliveira For some reason I was getting errors about a missing `schema_id`. I made [a few tweaks](https://github.com/ibrokemycomputer/gnome-shell-extension-ssh-quick-connect/commit/def7aca90449193012ff347361ddc727569e575b) and this is all working as expected on Gnome 45!
