### ISSUE TITLE
Flexible "Start Terminal Command"

### ISSUE THREAD

**Issue by careca1970** [ibrokemycomputer/gnome-shell-extension-ssh-quick-connect#3]
Hi there!
Thanks fpr the nice extension.

Please give a way to set the best fashion to start the terminal.
Different GUIs may have different ways to call the standard terminal.
Ex. at Fedora "x-terminal-emulator" does NOT work at all.

BR

**Comment by ibrokemycomputer** [comment]
This is a WIP
https://github.com/ibrokemycomputer/gnome-shell-extension-ssh-quick-connect/tree/ssh-PATH

If I dont get to it at least the base is there :)

**Comment by luixal** [comment]
Hi!

I'm too lazy to create the settings window so... I'm using an ugly workaround.

If you have a look at the code, you'll notice [line 94 at extention.js](https://github.com/ibrokemycomputer/gnome-shell-extension-ssh-quick-connect/blob/48e0daef99783ec092fdfbea3bfafda8ade061a6/extension.js#L94) showing the command run when an item is clicked. The terminal run is this:

```sh
x-terminal-emulator -e ssh <item>
```

where item is the entry in the `~/.ssh/config` file.

My favourite terminal (right now, at least) is Tilix so I just created a symbolic link so `x-terminal-emulator` launches `tilix`:

```sh
sudo ln -s /usr/bin/tilix /usr/bin/x-terminal-emulator
```
Hope this helps you! :)

**Comment by luixal** [comment]
Totally agreed.

It's just a dirty hack that works for me at the moment as I don't have any command called like that :)

**Comment by ibrokemycomputer** [comment]
Alright, this should work by default on most distros now. See https://github.com/ibrokemycomputer/gnome-shell-extension-ssh-quick-connect/blob/c3f8eaec8e4a725e40324fcebae3f3d2b17ff8e9/extension.js#L181-L207 for the fix. I'll update the extensions site with a new zip soon.

I'm also in the middle of adding a setting for it so you'd be able to add whatever command you want :) Probably wont get that added until next week though.

**Comment by ibrokemycomputer** [comment]
BTW, the terminal start command should work more "unviversally" right now. 

Letting it be customizable will come soonish. (Its not hard, I just need to "do it" lol)

**Comment by ibrokemycomputer** [comment]
@careca1970 @luixal Finally! I Added a setting for a custom SSH start command. 

I also used VSCode's "terminal" command to launch the default terminal command on most distros so this should work "out of the box" for most ppl now.

Thank you for the suggestion!
