### ISSUE TITLE
Missing install instructions

### ISSUE THREAD

**Issue by dslotter** [ibrokemycomputer/gnome-shell-extension-ssh-quick-connect#7]
Please consider adding instructions on how to install this very useful extension. Thank you.

**Comment by ibrokemycomputer** [comment]
@dslotter There are no manual installation instructions that are specific to this extension. I did some Googling and this seems like a decent guide for users who aren't familiar with the process :smile: 

Download a [zip of this repo](https://github.com/ibrokemycomputer/gnome-shell-extension-ssh-quick-connect/archive/refs/heads/master.zip), then follow [this guide](https://www.pragmaticlinux.com/2021/06/manually-install-a-gnome-shell-extension-from-a-zip-file/#:~:text=Manually%20install%20the%20Gnome%20Extension%20using%20GUI%20applications) (starting from the "Manually install the Gnome Extension using GUI applications" section)

**Comment by ibrokemycomputer** [comment]
I will be updating the[ Gnome Shell Extension page](https://extensions.gnome.org/extension/3237/ssh-quick-connect/) soon, so you wont need to come here to manually install the latest version. I work a full time developer job where I'm stuck on a macOS desktop so I only get to these convenience projects every so often :disappointed:
